[package]
name = "blockless-sdk"
version = "0.1.3"
authors = ["Join.G"]
description = "blockless runtime sdk"
keywords = ["blockless", "sdk"]
readme = "README.md"
edition = "2021"
license = "MIT/Apache-2.0"
repository = "https://github.com/blocklessnetwork/sdk-rust"

[dependencies]
json = "0.12"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
