name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  check-clippy-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.85.0
        with:
          toolchain: stable
          targets: wasm32-wasip1
          components: rustfmt,clippy
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all-features --all-targets -- -D warnings
      - name: Check
        run: cargo check --release --all --all-features
      - name: Test
        run: cargo test --features mock-ffi
